#!/bin/bash
total 20 drwxr-xr-x 2 root root 80 Nov 30 04:55 . drwxr-xr-x 4 root root 43 Nov 30 01:52 .. -rw-r--r-- 1 root root 12 Nov 30 05:02 0-current_working_directory -rw-r--r-- 1 root root 20 Nov 30 02:00 README.md -rw-r--r-- 1 root root 12288 Nov 30 01:58 .README.md.swp
