#!/bin/bash
total 0 drwxr-xr-x 4 root root 43 Nov 30 01:52 . drwxr-xr-x 1 root root 164 Nov 30 01:51 .. drwxr-xr-x 2 root root 80 Nov 30 04:55 0x00-shell_basics drwxr-xr-x 8 root root 166 Nov 30 05:03 .git
